Update deprecated Babel plugins
opensearch-project/oui pull request #1155
Opened 2023-11-15 00:40 UTC by JohnathonBowers

### Description
These changes update two deprecated Babel plugins in the OUI devDependencies list. The deprecated `@babel/plugin-proposal-class-properties` is replaced with `@babel/plugin-transform-class-properties`. Likewise, the deprecated `@babel/plugin-proposal-object-rest-spread` is replaced with `@babel/plugin-transform-object-rest-spread`.

After the changes, `yarn build`, `yarn build-docs`, and `yarn test` run successfully.

### Issues Resolved
Fixes #1130 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-04 17:59 UTC, BSFishy approved these changes

2023-12-04 20:59 UTC, joshuarrrr requested changes
@JohnathonBowers I think you also need to update the comments and usage in the `.babelrc` file here: https://github.com/opensearch-project/oui/blob/24592a68111ab47d511fc250ed18ef03ccac6f25/.babelrc.js#L34-L37

2023-12-11 19:25 UTC, JohnathonBowers commented
> @JohnathonBowers I think you also need to update the comments and usage in the `.babelrc` file here:
> 
> https://github.com/opensearch-project/oui/blob/24592a68111ab47d511fc250ed18ef03ccac6f25/.babelrc.js#L34-L37

Thanks for pointing this out, @joshuarrrr ! I've made the changes in `.babelrc.js` and pushed a new commit.

2023-12-11 22:04 UTC, joshuarrrr approved these changes

2023-12-11 22:05 UTC, merged