[OUI] Removed figma link/icon, Codesandbox link/icon, Sketch link/icon Casc…
opensearch-project/oui pull request #164
Opened 2022-12-23 18:21 UTC by AbhishekReddy1127

Signed-off-by: AbhishekReddy1127 <nallamsa@amazon.com>

### Description
Removed Figma, Codesandbox, Sketch link and icon.
Removed Cascadia options and Babelfish from theme dropdown.
 
### Issues Resolved
#111 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-27 23:18 UTC, KrooshalUX approved these changes
Based on descriptions in the PR, this matches the prescribed changes in 111. LGTM!

2022-12-30 18:12 UTC, BSFishy requested changes

2022-12-30 18:12 UTC, BSFishy commented on src-docs/src/components/guide_page/guide_page_header.tsx
> -          {renderCodeSandbox()}
Are these components used anywhere else? If not, can the components themselves be deleted?

2022-12-30 18:12 UTC, BSFishy commented on src-docs/src/components/guide_theme_selector/guide_theme_selector.tsx
> -  selectedLocale,
If these props aren't being used anymore, can they be removed from the props interface?

2023-01-04 00:33 UTC, BSFishy approved these changes

2023-01-04 19:46 UTC, ashwin-pc reviewed
Why was the call made to remove locale selection?

2023-01-04 20:00 UTC, KrooshalUX commented
@ashwin-pc  because we cannot support it right now - please see the original task in the issue #111 was to "Remove Babelfish (comment out pending further testing and localization strategy)"

2023-01-06 18:04 UTC, merged