Updated text in Section Positions
opensearch-project/oui pull request #235
Opened 2023-01-20 04:27 UTC by AbhishekReddy1127

Signed-off-by: AbhishekReddy1127 <nallamsa@amazon.com>

### Description
Changed the text in the section Positions from "Scroll to see!" to "Scroll for demo"
![Screen Shot 2023-01-19 at 8 23 25 PM](https://user-images.githubusercontent.com/62020972/213616888-ce6c0c17-a14e-4dc6-a50d-8d910aceb18e.png)
 
### Issues Resolved
#172 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-20 19:44 UTC, BSFishy requested changes

2023-01-20 19:44 UTC, BSFishy commented on src-docs/src/views/bottom_bar/bottom_bar_position.js
> +          <p>Scroll to demo</p>
The issue requests that it be specifically `Scroll for demo` rather than `to`

2023-01-23 20:48 UTC, BSFishy approved these changes

2023-02-03 03:42 UTC, KrooshalUX approved these changes
LGTM

2023-02-13 19:29 UTC, merged