Update README.md
opensearch-project/oui pull request #25
Opened 2022-08-09 05:35 UTC by KrooshalUX

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-17 00:19 UTC, bandinib-amzn reviewed
Can you please fix failed DCO?

2022-08-17 01:10 UTC, ashwin-pc approved these changes

2022-08-17 01:12 UTC, ashwin-pc requested changes
Fix DCO. When creating a commit to PR, add the `-s` flag to signoff on a commit.

In this instance, just ammend the latest commit using 

```
git commit --amend --signoff
```

2022-08-18 20:01 UTC, AMoo-Miki commented
Spoke to Kroosh: I will take care of this in my PR.

2022-08-18 20:01 UTC, closed without merging