Updated link Validation section
opensearch-project/oui pull request #270
Opened 2023-02-03 07:02 UTC by AbhishekReddy1127

Signed-off-by: AbhishekReddy1127 <nallamsa@amazon.com>

### Description
Updated the links to the Opensearch website in the Links section.

![Screen Shot 2023-02-02 at 11 01 09 PM](https://user-images.githubusercontent.com/62020972/216533629-45766adf-58b5-4b2d-8f0a-22ef46e9371b.png)
![Screen Shot 2023-02-02 at 11 01 18 PM](https://user-images.githubusercontent.com/62020972/216533633-799d736b-92bd-4816-a2b1-a01fd55e12ee.png)

 
### Issues Resolved
#210 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-02-03 07:06 UTC, KrooshalUX requested changes
Correct Opensearch to OpenSearch

2023-02-07 20:13 UTC, BSFishy requested changes

2023-02-07 20:13 UTC, BSFishy commented on src-docs/src/views/link/link.js
> +      <OuiLink href=" https://Opensearch.org" target="_blank">
Could these be changed to not have a space before the url?

2023-02-07 20:13 UTC, BSFishy commented on src-docs/src/views/link/link.js
> +      <OuiLink href=" https://Opensearch.org" external>
See previous comment

2023-02-15 20:56 UTC, BSFishy approved these changes

2023-02-16 03:25 UTC, KrooshalUX commented
One note - I am unable to link this to issue 210 using the "development" feature in github, not sure why - calling out to make sure we close the appropriate issue on merge.

2023-02-20 17:05 UTC, merged