Implement Pink Elephant
opensearch-project/oui pull request #559
Opened 2023-03-03 23:32 UTC by AbhishekReddy1127

### Description
Implements the Pink Elephant and more broadly any theme in the future.
 
### Issues Resolved
Fixes #556 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-06 02:24 UTC, seanneumann commented
This is exciting. Can I see some screenshots when they're ready?

2023-03-06 21:08 UTC, BSFishy requested changes
Please update theme colors to match https://github.com/opensearch-project/oui/issues/521#issuecomment-1451101640

2023-03-06 21:08 UTC, BSFishy commented on src/themes/oui/oui_colors_pink_elephant.scss
> +
This whole file is indented with 1 space, which is causing build failure

2023-03-06 23:42 UTC, BSFishy requested changes

2023-03-06 23:42 UTC, BSFishy commented on src/themes/oui/oui_colors_pink_elephant.scss
> +$ouiColorInk: #4012BC;
This must remain at `#000`. Cannot change with theme

2023-03-06 23:42 UTC, BSFishy commented on src/themes/oui/oui_colors_pink_elephant.scss
> +$ouiColorInk: #4012BC;
Maybe update `$ouiTextColor` instead?

2023-03-06 23:42 UTC, BSFishy commented on src/themes/oui/oui_colors_pink_elephant.scss
> +$ouiPageBackgroundColor: shade($ouiColorLightestShade, 45%);
This should be
```scss
$ouiPageBackgroundColor: $ouiColorLightestShade;
```

The shade causes some absurd color shifting issues

2023-03-07 01:17 UTC, BSFishy approved these changes

2023-03-07 20:52 UTC, merged