Update home_vew.js
opensearch-project/oui pull request #72
Opened 2022-09-16 09:19 UTC by kgcreative

Signed-off-by: kgcreative <kvngar@amazon.com>

### Description
- remove unused HomeFooterElasticLogo
- Edit title to reference OpenSearch
- Edit paragraph text to reference OpenSearch
- Remove 'crafted with . . .' and replace with OpenSearch copyright notice
 
### Issues Resolved
n/a
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-16 14:53 UTC, AMoo-Miki requested changes

2022-09-16 14:53 UTC, AMoo-Miki commented on src-docs/src/views/home/home_view.js
> +                at at at the OpenSearch Project to build projects that share our
at?
at at?
at at at?
at at at at?

2022-09-16 16:27 UTC, kgcreative commented on src-docs/src/views/home/home_view.js
> +                at at at the OpenSearch Project to build projects that share our
Removed starwars reference

2022-09-16 16:35 UTC, AMoo-Miki approved these changes

2022-09-19 18:20 UTC, kaddy645 approved these changes

2022-09-21 16:35 UTC, merged