Bump cosmiconfig version to 8.1.3
opensearch-project/oui pull request #737
Opened 2023-04-25 20:43 UTC by BSFishy

### Description
Bump `cosmiconfig` version to 8.1.3. `cosmiconfig` version 8.0.0 changed from `yaml` to `js-yaml`, which will resolve the issue.

### Issues Resolved
Fixes #733 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] All tests pass
  - [x] `yarn lint`
  - [x] `yarn test-unit`
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-26 00:33 UTC, bandinib-amzn approved these changes

2023-04-26 00:40 UTC, bandinib-amzn requested changes
Looks like PR #734 bumping `cosmiconfig` version. Do we still need this PR?

2023-04-27 15:55 UTC, BSFishy commented
> Looks like PR #734 bumping `cosmiconfig` version. Do we still need this PR?

No, that PR won't pass `yarn build` or `yarn build-docs`. Version 5 of `postcss-loader` bumps the minimum Webpack version to 5 and we're still on 4. #584 to track that, but in the meantime, this should fix the issue

2023-06-28 17:28 UTC, joshuarrrr commented
@BSFishy Can this be closed, the linked issue is autoclosed by Mend.

2023-06-29 21:02 UTC, BSFishy commented
Yeah I don't think this is necessary anymore

2023-06-29 21:02 UTC, closed without merging