Docs site changes
opensearch-project/oui pull request #96
Opened 2022-10-26 19:08 UTC by KrooshalUX

### Description
Updates the getting started markdown file to remove references no longer relevant, including sample projects. 
 
### Issues Resolved

 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] All tests pass
  - [ ] `yarn lint`
  - [ ] `yarn test-unit`
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/oui/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-28 22:31 UTC, BSFishy reviewed
It looks like you included project files (`OUI/OUI.iml` and `oui.iml`), which I don't think should be included. Other than that, lgtm 👍

2022-10-28 22:31 UTC, BSFishy commented on src-docs/src/views/guidelines/getting_started.md
> +We recommend installing a node version manager: [nvm](https://github.com/creationix/nvm) is recommended.
Nitpick: This link redirects to https://github.com/nvm-sh/nvm, so I think we could just have that directly.

2022-10-28 23:00 UTC, AMoo-Miki requested changes
Can you please add *.iml to the `gitignore`?

2022-11-03 02:54 UTC, KrooshalUX commented
@BSFishy changes made
@AMoo-Miki added *.iml to gitignore - though I dont see that commit showing up here if it should.

also I made some manual commits because I was having an issue in the IDE (now resolved) , and I forgot to sign them off. I tried to follow various how-to's on resolving, but nothing seemed to work other than manually setting it to pass. The option to do so only showed on one commit, however. Sadly, I think I need some hand holding to resolve.

2022-11-08 00:54 UTC, bandinib-amzn approved these changes
LGTM!

2022-11-08 20:35 UTC, BSFishy approved these changes

2022-11-22 20:02 UTC, joshuarrrr approved these changes

2023-02-23 01:08 UTC, AMoo-Miki approved these changes

2023-02-23 01:09 UTC, merged